# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/mahdi-zarei/sing
%global goihead sing
%global goipath github.com/mahdi-zarei/%{goihead}
Version:  0.6.6
%define oldver 0.6.6

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{?!tag:%{?!commit:%global tag v%{oldver}}}
%gometa -L -f


%global common_description %{expand:
Do you hear the people sing?.}

%global golicenses      LICENSE
%global godocs          README.md common/pipe/README.md\\\
                        common/x/list/README.md

Name:           golang-github-mahdi-zarei-sing
Release:        %autorelease
Summary:        Do you hear the people sing?

License:        GPL-3.0-only
URL:            %{gourl}
%define scommit %{?commit}%{?!commit:v%{version}}
%define stag %{?tag}%{?!tag:%scommit}
Source: https://%{goipath}/archive/%{stag}/%{goihead}-%{stag}.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep -A
shopt -s globstar

for i in **/* */*
do
  if test -f ${i}
  then
    sed -i "s~github.com/sagernet/sing~github.com/mahdi-zarei/sing~g;" "${i}"
  fi
done


%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check

%endif
%endif

%gopkgfiles

%changelog
%autochangelog
